Feature/task 1
ann-maier/react-redux pull request #1
Opened 2019-03-07 21:02 UTC by ann-maier

2019-03-11 10:18 UTC, ghost requested changes

2019-03-11 10:18 UTC, ghost commented on src/components/User/User.tsx
> +                <p>{`age: ${age}`}</p>
no sense of using template strings inside jsx tags 
```jsx
<p>age: {age}</p>
```

2019-03-11 10:18 UTC, KITSEPAMIgorSergiienko commented on src/App.tsx
> +      searchNameInput: searchType === SEARCH_NAME_TEMPLATE ? input : '',
just save `searchNameInput` and `searchCityInput` values in state

and `filter` users inside `render`

2019-03-11 10:18 UTC, KITSEPAMIgorSergiienko commented on src/App.tsx
> +    fetch(REQUEST_URL)
lets use `axios` for fetching

2019-03-11 10:18 UTC, KITSEPAMIgorSergiienko commented on src/App.tsx
> +      ? user.name.first.includes(input.toLowerCase())
please add the possibility to filter both on name and city

2019-03-11 10:18 UTC, KITSEPAMIgorSergiienko commented on src/App.tsx
> +                    handleOnChange={this.handleOnChange.bind(this)} />
you shouldn't use `bind` inside `render`, because you creating new function on every render

you can either bind it inside `constructor` either use class arrow function
```tsx
handleChange = () => {
}
```

2019-03-11 10:18 UTC, KITSEPAMIgorSergiienko commented on src/App.tsx
> +          this.state.isLoadingFailed
you are using `state` fields a lot here. let's destructure it at first line of `render`

2019-03-11 15:01 UTC, ghost approved these changes

2019-03-11 15:01 UTC, ghost commented on src/App.tsx
> +    if (searchInput && filteredUsers.length) {
```jsx
if (searchInput) {
 renderedUsers = filteredUsers.length ? this.getUsers(filteredUsers) : NO_SEARCH_RESULTS_TEMPLATE;
) else

2019-03-11 15:01 UTC, ghost commented on src/App.dictionary.ts
> +export const SEARCH_NAME_TEMPLATE: string = 'Name';
why it named `template`? maybe `type`?

2019-03-11 15:01 UTC, KITSEPAMIgorSergiienko commented on src/components/User/User.tsx
> +const User = ({ name, city, age, picture }: { name: Name, city: string, age: number, picture: string }) => {
would be nice to use `React.memo` here to avoid rerendering

2019-03-11 15:02 UTC, ghost approved these changes

2019-03-11 15:35 UTC, KITSEPAMBohdanHuseinov commented on src/App.tsx
> +    if (searchInput && filteredUsers.length) {
and ideally hide all of this logic inside separate function to have more clear render

2019-03-12 11:22 UTC, KITSEPAMIgorSergiienko commented
👍 let's merge and proceed to task 2

2019-03-13 10:43 UTC, merged